from app import db

class PA_OP_Registration(db.Model):
    __tablename__ = 'pa_op_registration'
    hospitalno = db.Column(db.String(30), primary_key=True)
    hospitalname = db.Column(db.String(60))
    visitnumber = db.Column(db.String(50), primary_key=True)
    patientid = db.Column(db.String(30))
    patientname = db.Column(db.String(60))
    sexcode = db.Column(db.String(2))
    sexname = db.Column(db.String(20))
    birthday = db.Column(db.DateTime)
    currentage = db.Column(db.Float)
    medicalrecordno = db.Column(db.String(40))
    cardno = db.Column(db.String(40))
    cardkidcode = db.Column(db.String(20))
    cardkindname = db.Column(db.String(40))
    idcard = db.Column(db.String(50))
    patientsource = db.Column(db.String(4))
    appointmentid = db.Column(db.String(60))
    specialpatflag = db.Column(db.String(10))
    ybindcode = db.Column(db.String(62))
    ybkindname = db.Column(db.String(60))
    ybcode = db.Column(db.String(20))
    ybname = db.Column(db.String(60))
    ybaccountno = db.Column(db.String(60))
    parentregdeptcode = db.Column(db.String(20))
    parentregdeptname = db.Column(db.String(60))
    regdeptcode = db.Column(db.String(20))
    regdeptname = db.Column(db.String(60))
    regdoctorcode = db.Column(db.String(20))
    regdoctorname = db.Column(db.String(60))
    acceptdeptcode = db.Column(db.String(20))
    acceptdeptname = db.Column(db.String(60))
    acceptedphysiciancode = db.Column(db.String(20))
    acceptedphysicianname = db.Column(db.String(60))
    settlekindcode = db.Column(db.String(20))
    settlekindname = db.Column(db.String(60))
    regkindcode = db.Column(db.String(20))
    regkindname = db.Column(db.String(60))
    acceptkindcode = db.Column(db.String(20))
    acceptkindname = db.Column(db.String(60))
    bookingregsourcecode = db.Column(db.String(20))
    bookingregsourcename = db.Column(db.String(60))
    regdate = db.Column(db.DateTime, primary_key=True)
    regdatezone = db.Column(db.String(30))
    accepteddate = db.Column(db.DateTime)
    returnregdate = db.Column(db.DateTime)
    staffcode = db.Column(db.String(20))
    staffname = db.Column(db.String(60))
    recordstatuscode = db.Column(db.String(2))
    recordstatusname = db.Column(db.String(20))
    triagecode = db.Column(db.String(2))
    triagename = db.Column(db.String(20))
    visitflagcode = db.Column(db.String(2))
    visitflagname = db.Column(db.String(20))
    visittype = db.Column(db.String(2))
    lastvisitnumber = db.Column(db.String(20))
    chargeserialno = db.Column(db.String(50))
    returnchargserialno = db.Column(db.String(50))
    specialtypeflag = db.Column(db.String(10))
    visitnumberid = db.Column(db.Integer)
    str1 = db.Column(db.String(200))
    str2 = db.Column(db.String(200))
    str3 = db.Column(db.String(200))
    str4 = db.Column(db.String(200))
    str5 = db.Column(db.String(200))
    str6 = db.Column(db.String(200))
    num1 = db.Column(db.Float)
    num2 = db.Column(db.Float)
    date1 = db.Column(db.DateTime)
    date2 = db.Column(db.DateTime)
    resourcetable = db.Column(db.String(200), primary_key=True)
    resourcetablekey = db.Column(db.String(200), primary_key=True)
    resourcetablekeyvalue = db.Column(db.String(200), primary_key=True)
    isdeleted = db.Column(db.Integer)
    lastupdatedttm = db.Column(db.DateTime)
    lastimportdttm = db.Column(db.DateTime)
    str7 = db.Column(db.String(200))
    str8 = db.Column(db.String(200))





